In [1]:
import camelot
import pandas as pd

file = "/Users/charleskramer/Documents/ISYE6644/references/1-s2.0-S001999586890973X-main.pdf"

tables = camelot.read_pdf(file,pages='2-8',flavor="stream")

In [13]:
#patching
#also:
# replace I with 1
# replace $ with 3
tables[0].df
tables[0].df.iloc[16,1] = '1, 4, 7'
tables[0].df.iloc[23,1] = '3, 7'
tables[0].df.iloc[32,1] = '4, 8, 14'
tables[0].df.iloc[37,1] = '5, 14, 20, 21'
tables[0].df.iloc[13,3] = '4, 16, 35'
tables[0].df.iloc[28,3] = '4, 7, 8, 16, 17, 28, 37, 43, 49, 52'
tables[0].df.iloc[34,3] = '33, 45'
tables[0].df.iloc[34,3] = '8, 35'
tables[0].df.iloc[36,3] = '18, 30'
tables[0].df.iloc[38,3] = '19, 37, 45, 55'
tables[0].df.iloc[46,2] = '137'



tables[0].df

,0,1,2,3
0,542,,ZIERLER AND BRILLHART,
1,,,T A B L E 1,
2,,,COMPLET~ LISTING OF IRREDUCIBLE TRINOMIALS,(MOD 2)
3,,"x'*--bx k ' - ~ l ,","2_-< n - < \n1000,",1~_ k ~ n/2
4,n,k,n,k
5,2,1,65,"18, 32"
6,3,1,66,3
7,4,1,68,"9, 33"
8,5,2,71,"6, 9, 18, 20, 35"
9,6,"1, 3",73,"25, 28, 31"
10,7,"1, 3",74,35
11,9,"1, 4",76,21
12,10,3,79,"9, 19"
13,11,2,81,"4, 16, 35"
14,12,"3, 5",84,"5, 9, 11, I3, 27, 35, 39"
15,14,5,86,21
16,15,"1, 4, 7",87,13
17,17,"3, 5, 6",89,38
18,18,"3, 7, 9",90,27
19,20,"3, 5",92,21
20,21,"2, 7",93,2
21,22,1,94,21
22,23,"5, 9",95,"11, I7"
23,25,"3, 7",97,"6, 12, 33, 34"
24,28,"I, 3, 9, 13",98,"11, 27"
25,29,2,100,"15, 19, 25, 37, 49"
26,30,"1, 9",102,"29, 37"
27,31,"3, 6, 7, 13",103,"9, 13, 30, 31"
28,33,"10, 13",105,"4, 7, 8, 16, 17, 28, 37, 43, 49, 52"
29,34,7,106,15
30,35,2,108,"17, 27, 31, 33, 45"
31,36,"9, 11, 15",110,33
32,39,"4, 8, 14",111,"I0, 49"
33,41,"3, 20",113,"9, 15, 30"
34,42,7,118,"8, 35"
35,44,5,119,"8, 88"
36,46,1,121,"18, 30"
37,47,"5, 14, 20, 21",123,2
38,49,"9, I2, 15, 22",124,"19, 37, 45, 55"
39,52,"3, 7, 19, 21",126,"21, 49"
40,54,"9, 21, 27",127,"1, 7, 15, 30, 63"
41,55,"7, 24",129,"5, 31, 46"
42,57,"4, 7, 22, 25",130,3
43,58,19,132,"17, 29"
44,60,"1, 9, I1, 15, 17, 23",134,57
45,62,29,135,"11, 16, 22, 29"
46,63,"1, 5, 11, 28, $1",137,"21, 35, 57"

In [14]:
klist = tables[0].df.iloc[17,1]
kl = [int(k) for k in klist.split(',')]
kl

[3, 5, 6]

In [15]:
df1 = tables[0].df.iloc[:,0:2]
df1.rename(columns={0:"n",1:"k"},inplace=True)
df2 = tables[0].df.iloc[:,2:]
df2.rename(columns={2:"n",3:"k"},inplace=True)
df = pd.concat([df1,df2])
df.drop(index=[0,1,2,3,4],inplace=True)
df.reset_index(inplace=True)
df

/var/folders/12/lnw3jf817_x0g5w5q1l9d8x00000gn/T/ipykernel_17430/69773849.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df1.rename(columns={0:"n",1:"k"},inplace=True)
/var/folders/12/lnw3jf817_x0g5w5q1l9d8x00000gn/T/ipykernel_17430/69773849.py:4: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df2.rename(columns={2:"n",3:"k"},inplace=True)

    index    n                  k
0       5    2                  1
1       6    3                  1
2       7    4                  1
3       8    5                  2
4       9    6              1,  3
..    ...  ...                ...
79     42  130                  3
80     43  132            17,  29
81     44  134                 57
82     45  135  11,  16,  22,  29
83     46  137       21,  35,  57

[84 rows x 3 columns]

In [16]:
def klist(x):
    #print(x)
    kl = [int(k) for k in x.replace("$","3").replace("I","1").split(',')]
    return kl

x = "$,4,5"
type(x)
klist(x)

[3, 4, 5]

In [17]:
df["klist"] = df["k"].apply(klist)
df

    index    n                  k             klist
0       5    2                  1               [1]
1       6    3                  1               [1]
2       7    4                  1               [1]
3       8    5                  2               [2]
4       9    6              1,  3            [1, 3]
..    ...  ...                ...               ...
79     42  130                  3               [3]
80     43  132            17,  29          [17, 29]
81     44  134                 57              [57]
82     45  135  11,  16,  22,  29  [11, 16, 22, 29]
83     46  137       21,  35,  57      [21, 35, 57]

[84 rows x 4 columns]

In [18]:
#sample from df

from random import randint

m = df.shape[0]

for _ in range(100):
    n = df["n"][randint(0,m-1)]
    k = df["k"][randint(0,len(df.iloc[i,3])-1)]


print("done")

df.to_csv("primitive_trinomials.csv")

df["klist"][80][1]

done

29

In [19]:
df.to_pickle("primitive_trinomials")